namespace Library.ChineseEnums;

public static class StatChinese
{
    public static string GetTitle(Stat value)
    {
        switch (value)
        {
            case Stat.BaseHealth:
                return "基础生命值";
            case Stat.BaseMana:
                return "基础魔法值";
            case Stat.Health:
                return "生命值";
            case Stat.Mana:
                return "魔法值";
            case Stat.MinAC:
                return "防御";
            case Stat.MaxAC:
                return "防御";
            case Stat.MinMR:
                return "魔防";
            case Stat.MaxMR:
                return "魔防";
            case Stat.MinDC:
                return "破坏力";
            case Stat.MaxDC:
                return "破坏力";
            case Stat.MinMC:
                return "自然系魔法";
            case Stat.MaxMC:
                return "自然系魔法";
            case Stat.MinSC:
                return "灵魂系魔法";
            case Stat.MaxSC:
                return "灵魂系魔法";
            case Stat.Accuracy:
                return "准确度";
            case Stat.Agility:
                return "敏捷度";
            case Stat.AttackSpeed:
                return "攻击速度";
            case Stat.Light:
                return "光照范围";
            case Stat.Strength:
                return "力量";
            case Stat.Luck:
                return "幸运";
            case Stat.FireAttack:
                return "火";
            case Stat.FireResistance:
                return "火";
            case Stat.IceAttack:
                return "冰";
            case Stat.IceResistance:
                return "冰";
            case Stat.LightningAttack:
                return "雷";
            case Stat.LightningResistance:
                return "雷";
            case Stat.WindAttack:
                return "风";
            case Stat.WindResistance:
                return "风";
            case Stat.HolyAttack:
                return "神圣";
            case Stat.HolyResistance:
                return "神圣";
            case Stat.DarkAttack:
                return "暗黑";
            case Stat.DarkResistance:
                return "暗黑";
            case Stat.PhantomAttack:
                return "幻影";
            case Stat.PhantomResistance:
                return "幻影";
            case Stat.Comfort:
                return "舒适度";
            case Stat.LifeSteal:
                return "生命偷取";
            case Stat.ExperienceRate:
                return "经验倍率";
            case Stat.DropRate:
                return "掉落倍率";
            case Stat.SkillRate:
                return "技能熟练度倍率";
            case Stat.PickUpRadius:
                return "拾取范围";
            case Stat.Healing:
                return "总治疗量";
            case Stat.HealingCap:
                return "每次回复上限";
            case Stat.Invisibility:
                return "隐身";
            case Stat.FireAffinity:
                return "强火";
            case Stat.IceAffinity:
                return "强冰";
            case Stat.LightningAffinity:
                return "强雷";
            case Stat.WindAffinity:
                return "强风";
            case Stat.HolyAffinity:
                return "强神圣";
            case Stat.DarkAffinity:
                return "强暗黑";
            case Stat.PhantomAffinity:
                return "强幻影";
            case Stat.ReflectDamage:
                return "反伤";
            case Stat.Redemption:
                return "临时无辜状态";
            case Stat.HealthPercent:
                return "生命值";
            case Stat.CriticalChance:
                return "暴击率";
            case Stat.SaleBonus5:
                return "出售收益+5%";
            case Stat.SaleBonus10:
                return "出售收益+10%";
            case Stat.SaleBonus15:
                return "出售收益+15%";
            case Stat.SaleBonus20:
                return "出售收益+20%";
            case Stat.MagicShield:
                return "魔法盾";
            case Stat.Cloak:
                return "隐身";
            case Stat.CloakDamage:
                return "隐身伤害";
            case Stat.TheNewBeginning:
                return "新生充能";
            case Stat.Brown:
                return "灰名状态，他人可随意攻击";
            case Stat.PKPoint:
                return "PK值";
            case Stat.GlobalShout:
                return "无等级限制的全球喊话";
            case Stat.MCPercent:
                return "魔法攻击";
            case Stat.JudgementOfHeaven:
                return "天罚概率";
            case Stat.Transparency:
                return "透明度";
            case Stat.CelestialLight:
                return "生命值回复";
            case Stat.DarkConversion:
                return "魔法值转换";
            case Stat.RenounceHPLost:
                return "生命值回复";
            case Stat.BagWeight:
                return "背包重量";
            case Stat.WearWeight:
                return "穿戴重量";
            case Stat.HandWeight:
                return "手持重量";
            case Stat.GoldRate:
                return "金币倍率";
            case Stat.AvailableHuntGold:
                return "可用狩猎金币";
            case Stat.AvailableHuntGoldCap:
                return "最大可用狩猎金币";
            case Stat.ItemReviveTime:
                return "复活冷却";
            case Stat.MaxRefineChance:
                return "最大强化概率";
            case Stat.CompanionInventory:
                return "宠物背包空间";
            case Stat.CompanionBagWeight:
                return "宠物背包重量";
            case Stat.DCPercent:
                return "物理攻击";
            case Stat.SCPercent:
                return "精神攻击";
            case Stat.CompanionHunger:
                return "宠物饥饿度";
            case Stat.PetDCPercent:
                return "宠物物理攻击";
            case Stat.BossTracker:
                return "地图上定位Boss怪物";
            case Stat.PlayerTracker:
                return "地图上定位玩家";
            case Stat.CompanionRate:
                return "宠物倍率";
            case Stat.WeightRate:
                return "重量倍率";
            case Stat.MagicDefencePercent:
                return "魔法防御";
            case Stat.PhysicalDefencePercent:
                return "物理防御";
            case Stat.ManaPercent:
                return "魔法值";
            case Stat.RecallSet:
                return "召回命令：@GroupRecall";
            case Stat.MonsterExperience:
                return "普通怪物基础经验";
            case Stat.MonsterGold:
                return "普通怪物基础金币";
            case Stat.MonsterDrop:
                return "普通怪物基础掉落率";
            case Stat.MonsterDamage:
                return "普通怪物基础伤害";
            case Stat.MonsterHealth:
                return "普通怪物基础生命";
            case Stat.CompanionCollection:
                return "改进宠物物品收集";
            case Stat.ProtectionRing:
                return "保护戒指";
            case Stat.BaseExperienceRate:
                return "基础经验倍率";
            case Stat.BaseGoldRate:
                return "基础金币倍率";
            case Stat.BaseDropRate:
                return "基础掉落倍率";
            case Stat.FrostBiteDamage:
                return "冰霜伤害";
            case Stat.MaxMonsterExperience:
                return "最大普通怪物基础经验";
            case Stat.MaxMonsterGold:
                return "最大普通怪物基础金币";
            case Stat.MaxMonsterDrop:
                return "最大普通怪物基础掉落率";
            case Stat.MaxMonsterDamage:
                return "最大普通怪物基础伤害";
            case Stat.MaxMonsterHealth:
                return "最大普通怪物基础生命";
            case Stat.CriticalDamage:
                return "暴击伤害 (PvE)";
            case Stat.Experience:
                return "经验";
            case Stat.DeathDrops:
                return "死亡掉落已启用";
            case Stat.PhysicalResistance:
                return "物理";
            case Stat.FragmentRate:
                return "每个碎片成功率";
            case Stat.MapSummoning:
                return "召唤地图概率";
            case Stat.FrostBiteChance:
                return "冰霜概率";
            case Stat.ParalysisChance:
                return "麻痹概率";
            case Stat.SlowChance:
                return "缓慢概率";
            case Stat.SilenceChance:
                return "沉默概率";
            case Stat.BlockChance:
                return "格挡概率";
            case Stat.EvasionChance:
                return "闪避概率";
            case Stat.PoisonResistance:
                return "毒素抗性";
            case Stat.Rebirth:
                return "转生";
            case Stat.Focus:
                return "专注";
            case Stat.GrowthLevel:
                return "成长等级";
            case Stat.Invincibility:
                return "你对所有伤害免疫";
            case Stat.SuperiorMagicShield:
                return "吸收能量";
            case Stat.DefensiveMastery:
                return "防御精通";
            case Stat.SoulResonance:
                return "你与另一名玩家灵魂绑定";
            case Stat.ElementalSwords:
                return "元素剑";
            case Stat.ThrowDistance:
                return "投掷距离";
            case Stat.AutoCast:
                return "自动施法";
            case Stat.Flexibility:
                return "灵活性";
            case Stat.FloatStrength:
                return "漂浮强度";
            case Stat.ReelBonus:
                return "收杆奖励";
            case Stat.NibbleChance:
                return "咬钩概率";
            case Stat.FinderChance:
                return "发现概率";
            case Stat.Duration:
                return "持续时间";
            default:
                return value.ToString();
        }
    }
}